// js/dkf.js
// Export to DAT/EM Keypad (.dkf) format.
//
// Format derived from sample ESP_Survey_ACAD.dkf:
// - Plain ASCII, CRLF line endings, tab-indented fields
// - Each LAYER holds a fixed 14 cols x 18 rows = 252 button grid,
//   numbered row-major from top-left starting at 1
// - Button macros use {RET} where AutoCAD uses ; for Enter
//
// v1 scope (see TASKS.md):
// - Single LAYER named "Main"
// - All cells emitted as 1x1 (no multi-cell spans, no headers, no bitmaps)
// - User's rows x cols placed top-left; remaining slots are empty buttons
// - One LABEL block per button (no stacked text)

import { colorByID, cellOwnerMap, normalizeMacro } from "./state.js";

export const DKF_COLS = 14;
export const DKF_ROWS = 18;
const DKF_TOTAL = DKF_COLS * DKF_ROWS;

function hexToRgb(hex) {
  const n = parseInt(hex.replace("#", ""), 16);
  return `${(n >> 16) & 0xff};${(n >> 8) & 0xff};${n & 0xff}`;
}

// Editor-form macro -> .dkf DATA line.
//
// The editor convention stores macros in DAT/EM-ready form (literal {RET}
// tokens, no cancel prefix, single line). Export is just a normalization
// pass (catches anything pasted in legacy ^C^C / `;` form) plus a trailing
// {RET} to commit the final keystroke. DAT/EM's keystroke injection does
// not honor `^C^C` or `{ESC}` as cancel, so normalizeMacro strips them.
export function macroToDkf(commands) {
  let out = normalizeMacro(commands);
  if (out && !out.endsWith("{RET}")) out += "{RET}";
  return out;
}

function dkfTimestamp(d = new Date()) {
  const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const months = ["January", "February", "March", "April", "May", "June",
                  "July", "August", "September", "October", "November", "December"];
  const dd = String(d.getDate()).padStart(2, "0");
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return {
    date: `${days[d.getDay()]}, ${months[d.getMonth()]} ${dd} ${d.getFullYear()}`,
    time: `${hh}:${mm}`,
  };
}

function safeFilenameStem(name) {
  return (name || "keypad").replace(/[^A-Za-z0-9_]+/g, "_") || "keypad";
}

export function buildDkfExport(project) {
  const ts = dkfTimestamp();
  const lines = [
    "*Generated by the DAT/EM Keypad",
    "",
    `Filename: ${safeFilenameStem(project.name)}.dkf`,
    "",
    `*Date: ${ts.date}`,
    `*Time: ${ts.time}`,
    "",
    "PORTRAIT: YES",
    "ACTIVE_LAYER: Main",
    "",
    "",
    "LAYER: Main",
    "",
  ];

  const owner = cellOwnerMap(project);
  const cellToN = (r, c) => r * DKF_COLS + c + 1;

  for (let n = 1; n <= DKF_TOTAL; n++) {
    const row = Math.floor((n - 1) / DKF_COLS);
    const col = (n - 1) % DKF_COLS;
    const inUserGrid = row < project.rows && col < project.cols;
    const ownerKey = inUserGrid ? owner[`${row},${col}`] : null;

    lines.push(`BUTTON:${n}`);

    if (!ownerKey) {
      // empty cell or outside user's grid
      lines.push("\tBUTTON SHAPE: 1 1");
      continue;
    }

    if (ownerKey !== `${row},${col}`) {
      // slave cell — points at master
      const [mr, mc] = ownerKey.split(",").map(Number);
      lines.push(`\tSTART BUTTON: ${cellToN(mr, mc)}`);
      continue;
    }

    // master cell with content
    const btn = project.buttons[ownerKey];
    const w = btn.width || 1;
    const h = btn.height || 1;
    lines.push(`\tBUTTON SHAPE: ${w} ${h}`);
    if (btn.header) lines.push("\tHEADER: TRUE");
    const cat = colorByID(btn.color);
    lines.push(`\tBACKGROUND COLOR: ${hexToRgb(cat.hex)}`);
    const cmds = (btn.commands || "").trim();
    if (cmds) lines.push(`\tDATA: ${macroToDkf(cmds)}`);
    // Split label on " / " (with surrounding spaces) and newlines into
    // separate LABEL blocks. DAT/EM Keypad Controller renders each block on
    // its own line — collapsing to a single block causes cell truncation.
    // Matches the join in dkf-import.js for lossless round-trip.
    const label = (btn.label || "").trim();
    if (label) {
      const segments = label.split(/ \/ |\n/).map((s) => s.trim()).filter((s) => s.length);
      for (const seg of segments) {
        lines.push("\tLABEL:");
        lines.push(`\t\tLABEL TEXT:${seg}`);
      }
    }
    // Bitmap icon (e.g. cross.bmp) — DAT/EM stores it as a separate LABEL
    // block with IS TEXT: FALSE. Emitted after text labels.
    const bitmap = (btn.bitmap || "").trim();
    if (bitmap) {
      lines.push("\tLABEL:");
      lines.push("\t\tIS TEXT:FALSE");
      lines.push(`\t\tBITMAP NAME:${bitmap}`);
    }
  }

  return lines.join("\r\n") + "\r\n";
}

// Returns a human-readable warning if the project's grid exceeds the DAT/EM
// keypad size (14x18). Null if it fits.
export function dkfClampWarning(project) {
  const overflow = [];
  if (project.rows > DKF_ROWS) overflow.push(`${project.rows} rows > ${DKF_ROWS}`);
  if (project.cols > DKF_COLS) overflow.push(`${project.cols} cols > ${DKF_COLS}`);
  if (!overflow.length) return null;
  return `Grid exceeds DAT/EM keypad (${overflow.join(", ")}); truncated to top-left ${DKF_COLS}x${DKF_ROWS}.`;
}

export function dkfFilename(project) {
  return `${safeFilenameStem(project.name)}.dkf`;
}
